name: Build & Package

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Package App
        run: yarn package
      - name: Get Short Commit Hash
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: ZIP App
        run: zip -r ${{ steps.vars.outputs.sha_short }}.zip out
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Mac Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: ${{ steps.vars.outputs.sha_short }}.zip
           asset_name: ${{ steps.vars.outputs.sha_short }}.zip
           asset_content_type: application/zip